openapi: 3.0.3
info:
  title: My JSON Server API
  description: API for retrieving Greek gods data from external service
  version: 1.0.0
  contact:
    name: Juan Antonio Breña Moral
    email: my@email.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
servers:
  - url: https://my-json-server.typicode.com/jabrena/latency-problems
    description: External JSON server
paths:
  /greek:
    get:
      tags:
        - External Greek Gods
      summary: Get Greek gods from external API
      description: Returns a list of Greek gods from the external service
      operationId: getExternalGreekGods
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
              examples:
                success:
                  value:
                    - "Zeus"
                    - "Hera"
                    - "Poseidon"
                    - "Demeter"
                    - "Ares"
                    - "Athena"
                    - "Apollo"
                    - "Artemis"
                    - "Hephaestus"
                    - "Aphrodite"
                    - "Hermes"
                    - "Dionysus"
                    - "Hades"
                    - "Hypnos"
                    - "Nike"
                    - "Janus"
                    - "Nemesis"
                    - "Iris"
                    - "Hecate"
                    - "Tyche"
        '500':
          description: Internal server error
        '504':
          description: Gateway timeout
  /roman:
    get:
      tags:
        - External Roman Gods
      summary: Get Roman gods from external API
      description: Returns a list of Roman gods from the external service
      operationId: getExternalRomanGods
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
              examples:
                success:
                  value:
                    - "Venus"
                    - "Mars"
                    - "Neptun"
                    - "Mercury"
                    - "Pluto"
                    - "Jupiter"
        '500':
          description: Internal server error
        '504':
          description: Gateway timeout
  /nordic:
    get:
      tags:
        - External Nordic Gods
      summary: Get Nordic gods from external API
      description: Returns a list of Nordic gods from the external service
      operationId: getExternalNordicGods
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
              examples:
                success:
                  value:
                    - "Baldur"
                    - "Freyja"
                    - "Heimdall"
                    - "Frigga"
                    - "Hel"
                    - "Loki"
                    - "Njord"
                    - "Odin"
                    - "Thor"
                    - "Tyr"
        '500':
          description: Internal server error
        '504':
          description: Gateway timeout
  /indian:
    get:
      tags:
        - External Indian Gods
      summary: Get Indian gods from external API
      description: Returns a list of Indian gods from the external service
      operationId: getExternalIndianGods
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
              examples:
                success:
                  value:
                    - "Brahma"
                    - "Vishnu"
                    - "Shiva"
                    - "Ganapati"
                    - "Rama"
                    - "Krishna"
                    - "Saraswati"
                    - "Lakshmi"
                    - "Durga Devi"
                    - "Indra"
                    - "Surya"
                    - "Agni"
                    - "Hanuman"
        '500':
          description: Internal server error
        '504':
          description: Gateway timeout
  /celtiberian:
    get:
      tags:
        - External Celtiberian Gods
      summary: Get Celtiberian gods from external API
      description: Returns a list of Celtiberian gods from the external service
      operationId: getExternalCeltibrianGods
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
              examples:
                success:
                  value:
                    - "Ataecina"
                    - "Candamius"
                    - "Cariociecus"
                    - "Dercetius"
                    - "Duillae"
                    - "Eacus"
                    - "Endouellicus"
                    - "Semnocosus"
        '500':
          description: Internal server error
        '504':
          description: Gateway timeout
components:
  schemas:
    ExternalGod:
      type: string
