@startuml
participant Consumer
participant Greek
participant Roman
participant Nordic

Consumer -> Greek: GET /greek
Consumer -> Roman: GET /roman
Consumer -> Nordic: GET /nordic
Greek --> Consumer: List of gods
Roman --> Consumer: List of gods
Nordic --> Consumer: List of gods
note over Consumer, Greek: All response use the same Type

loop Stream
    Consumer -> Consumer: Filter
    Consumer -> Consumer: toDigits
    Consumer -> Consumer: sum
end
@enduml
